server:
  port: 80
spring:
  messages:
    basename: properties/message
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka:eureka@eureka-7001.com:7001/eureka/,http://eureka:eureka@eureka-7002.com:7002/eureka/,http://eureka:eureka@eureka-7003.com:7003/eureka/