server:
  port: 80
  
logging:
  level:
    com.liuxc.microcloud.service: debug #数据接口的信息
    
feign:
  hystrix:
    enabled: true
  compression:
    request:
      mime-types: #配置能够压缩的类型
        - txt/xml
        - application/xml
        - application/json
      min-request-size: 2048 #超过2048的字节的请求需要被压缩
        
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka:eureka@eureka-7001.com:7001/eureka/,http://eureka:eureka@eureka-7002.com:7002/eureka/,http://eureka:eureka@eureka-7003.com:7003/eureka/