server:
  port: 80
ribbon:
  euerKa:
    enabled: false  #关闭启用eureKa
microcloud-provider-dept:
   ribbon:
      listOfservers: http://provider-8001.com:8001,http://provider-8002.com:8002,http://provider-8003.com:8003 #ribbon 可访问的主机地址
   
      
    

    
   
    
    